name: cibil_score_app
description: A Flutter app for CIBIL score improvement using AI.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  provider: ^6.0.0  # Add this line to include the provider packa
  google_generative_ai: ^0.4.5
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
